### ISSUE TITLE
anthoscli error creating management cluster - problem with workloadmetadata config for the nodepool

### ISSUE THREAD

**Issue by melihsqsp** [kubeflow/gcp-blueprints#108]
Instructions at https://master.kubeflow.org/docs/gke/deploy/management-setup/ fail when running `make apply` with error `W0730 16:41:44.602361   64639 nodepool.go:441] unsupported change: {Path:Config.WorkloadMetadataConfig.Mode Actual:GKE_METADATA Expected:}` due to `./.build/cluster/container.cnrm.cloud.google.com_v1beta1_containernodepool_kubeflow-manage-pool.yaml` with entry
````   
workloadMetadataConfig:
      mode: GKE_METADATA
```
no nodes are created in the cluster

**Comment by jlewi** [comment]
@melihsqsp can you try changing it to nodeMetadata as specified in the spec
https://cloud.google.com/config-connector/docs/reference/resource-docs/container/containernodepool

**Comment by melihsqsp** [comment]
I noticed that the top of file `./.build/cluster/container.cnrm.cloud.google.com_v1beta1_containernodepool_kubeflow-manage-pool.yaml` file looks like this:
```
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  annotations:
    gke.io/cluster: bootstrap://
  clusterName: mgmt-project-id/mgmt-location/mgmt-name
````
the clusterName was set to `clusterName: mgmt-project-id/mgmt-location/mgmt-name` without values being replaced.

Running this manually with ` anthoscli apply --project=<prof_name> -f ./.build/cluster/container.cnrm.cloud.google.com_v1beta1_containernodepool_kubeflow-manage-pool.yaml` 
fails with 
```I0803 01:26:36.554645   36729 main.go:230] reconcile container.cnrm.cloud.google.com/ContainerNodePool kubeflow-manage-pool
Unexpected error: error reconciling objects: error reconciling ContainerNodePool:<project_name>/<cluster_name>-pool: no clusters found matching name <project_name>/<cluster_name> with gke.io/cluster bootstrap://
```
Next, I manually edited the file as the clusterName looks like it didn't substitute during `make apply`, and remove the annotation completely so it looks like:
```
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  clusterName: <project_name>/<location>/<cluster_name>
  name: kubeflow-manage-pool
  namespace: <project_name>
```
where `<project_name>/<location>/<cluster_name>` are the actual strings for each. After a pause, this fails with 
```
Unexpected error: error connecting to cluster "<project_name>/<location>/<cluster_name>": error connecting to GKE cluster <project_name>/<location>/<cluster_name>: unable to get "namespaces" /kube-system: Get "https://xxxxxx/api/v1/namespaces/kube-system": dial tcp xxxxxx:443: i/o timeout
```

**Comment by jlewi** [comment]
@melihsqsp What commit did you use for the management cluster and manifests?

You should be using at least 
https://github.com/kubeflow/gcp-blueprints/commit/0654b2d8f0c63f01417f03baab55d01c2320857e#diff-d10af457daa1deed54e2c36b5f295e7e

https://github.com/kubeflow/manifests/commit/4c1221c1d6b900be0f231e39edd737da6e524d1a

If your YAML files don't have proper values substituted in then it will not work. Is it possible to upload the YAML files so we can take a look?

The error

```
Unexpected error: error connecting to cluster "<project_name>/<location>/<cluster_name>": error connecting to GKE cluster <project_name>/<location>/<cluster_name>: unable to get "namespaces" /kube-system: Get "https://xxxxxx/api/v1/namespaces/kube-system": dial tcp xxxxxx:443: i/o timeout
```

Looks like a problem connecting to your GKE cluster. I would suggest checking the following

1. Does your GKE cluster exist
1. Can you do `kubectl get namespace` 
    * This will help diagnose any connectivity issues

What version of the anthoscli are you running

```
anthoscli version
```

If you are using a version older then 0.2.4 try upgrading using gcloud to the latest version.

When anthoscli creates your cluster it looks at both the container and nodepool YAML files. So both should exist and be properly configured.

**Comment by melihsqsp** [comment]
I used the instructions on `https://master.kubeflow.org/docs/gke/deploy/management-setup/ ` on a fresh project, and latest sources. It pulled from master `https://github.com/kubeflow/gcp-blueprints.git/management@master`. Inside the Makefile under ./management I see `MANIFESTS_URL=https://github.com/kubeflow/manifests.git/gcp/v2/management@master` which matches with the commit you pasted. Anthos cli `GitTag:"0.2.4"` Everything should be the latest.

For the 3 manifests, I see this output when I do `make apply`:
```
# Delete the directory so any resources that have been removed
# from the manifests will be pruned
rm -rf .build
mkdir -p .build/
mkdir -p .build/cluster
./kustomize build ./instance/cluster -o .build/cluster
anthoscli apply --project=kubeflow-corp-001 -f .build/cluster
Flag --project has been deprecated, GCE project flag is unused and deprecated
W0803 00:22:21.646717   12306 warning.go:14] manifest is using some deprecated features; please run vet for details
I0803 00:22:21.646803   12306 main.go:230] reconcile serviceusage.cnrm.cloud.google.com/Service container.googleapis.com
I0803 00:22:22.852833   12306 main.go:230] reconcile container.cnrm.cloud.google.com/ContainerCluster kubeflow-manage
creating gke cluster: done
I0803 00:52:10.315499   12306 main.go:230] reconcile container.cnrm.cloud.google.com/ContainerNodePool kubeflow-manage-pool
W0803 00:52:11.101539   12306 nodepool.go:441] unsupported change: {Path:Config.WorkloadMetadataConfig.Mode Actual:GKE_METADATA Expected:}
Reconciliation completed successfully
```
The other 2 yaml files do seem to have the substitutions, and appear to execute. In gcp I see the cluster that was created and I can configure kubectl command line access via the button next to it which gives the warning:
```gcloud container clusters get-credentials xxxxx
Fetching cluster endpoint and auth data.
WARNING: cluster kubeflow-manage is not running. The kubernetes API may not be available.
kubeconfig entry generated for kubeflow-manage.
```
When I do `kubectl get namespace:` I get  `Unable to connect to the server: dial tcp xxxx: i/o timeout`. We have other projects/clusters that I can connect just fine, so I think the problem is that the cluster did not come up to allow me connect.

Inside the project I see `Node pool` and `Instance group` that were created with green checkmarks. What I do not see is under `Nodes` there is nothing but an error mark with message `Sorry, the server was only able to partially fulfill your request. Some data might not be rendered.` 
`./.build/cluster/container.cnrm.cloud.google.com_v1beta1_containernodepool_kubeflow-manage-pool.yaml`: (where I manually modified the clusterName and masking the actual-strings for here:
```
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  clusterName: <project-name>/<location>/<cluster-name>
  name: <cluster-name>-pool
  namespace: <project-name>
spec:
  autoscaling:
    maxNodeCount: 3
    minNodeCount: 1
  clusterRef:
    name: kubeflow-manage
  management:
    autoRepair: true
    autoUpgrade: true
  nodeConfig:
    diskSizeGb: 100
    diskType: pd-standard
    machineType: n1-standard-4
    metadata:
      disable-legacy-endpoints: "true"
    oauthScopes:
    - https://www.googleapis.com/auth/devstorage.read_only
    - https://www.googleapis.com/auth/logging.write
    - https://www.googleapis.com/auth/monitoring
    - https://www.googleapis.com/auth/trace.append
    preemptible: false
    workloadMetadataConfig:
      mode: GKE_METADATA
```

`./.build/cluster/container.cnrm.cloud.google.com_v1beta1_containercluster_kubeflow-manage.yaml`:
```
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    gke.io/cluster: bootstrap://
  name: kubeflow-manage
  namespace: <project-name>
spec:
  initialNodeCount: 3
  location: us-east1-c
  releaseChannel:
    channel: REGULAR
  workloadIdentityConfig:
    identityNamespace: <project-name>.svc.id.goog
```
`./.build/cluster/serviceusage.cnrm.cloud.google.com_v1beta1_service_container.googleapis.com.yaml`:
```
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    cnrm.cloud.google.com/disable-dependent-services: "false"
  name: container.googleapis.com
  namespace: <project-name>
```

**Comment by melihsqsp** [comment]
as far as the manifests repo goes, this error happens during 2nd step at management cluster before manifests are needed or fetched

**Comment by jlewi** [comment]
Not sure what's happening. We'll have to try to reproduce. In the interim, you could create a cluster without using the anthos CLI; e.g. using gcloud and then just continue on to the next steps.

**Comment by jal06** [comment]
I have same error as @melihsqsp

I followed instructions from the [documentation](https://www.kubeflow.org/docs/gke/deploy/management-setup/)  and have same problem using manifest v1.1.0
`kpt pkg get https://github.com/kubeflow/gcp-blueprints.git/management@v1.1.0 ./`

When running `make apply` , I see a warning about the flag --project which has been deprecated 
But more important, I also see the warning about GKE_METADATA  at the end of the log
```
# Delete the directory so any resources that have been removed
# from the manifests will be pruned
rm -rf .build
mkdir -p .build/
mkdir -p .build/cluster
kustomize build ./instance/cluster -o .build/cluster
anthoscli apply --project=my_project -f .build/cluster
Flag --project has been deprecated, GCE project flag is unused and deprecated
W1012 09:19:15.347705   32473 warning.go:14] manifest is using some deprecated features; please run vet for details
I1012 09:19:15.347829   32473 main.go:230] reconcile serviceusage.cnrm.cloud.google.com/Service container.googleapis.com
I1012 09:19:17.322064   32473 main.go:230] reconcile container.cnrm.cloud.google.com/ContainerCluster kfmgmnt
creating gke cluster: done
I1012 09:23:16.666037   32473 main.go:230] reconcile container.cnrm.cloud.google.com/ContainerNodePool kfmgmnt-pool
W1012 09:23:17.657607   32473 nodepool.go:441] unsupported change: {Path:Config.WorkloadMetadataConfig.Mode Actual:GKE_METADATA Expected:}
Reconciliation completed successfully
```

Then I run `make create-ctxt` , I get error because the kubeflow cluster doesn't exist
```
PROJECT=my_project \
   REGION=europe-west1-b \
   NAME=kflow1 ./hack/create_context.sh
+ echo Checking if context kflow1 exists
Checking if context kflow1 exists
+ kubectl config use-context kflow1
error: no context exists with the name: "kflow1"
+ RESULT=1
+ '[' 1 -eq 0 ']'
+ set -ex
+ gcloud --project=my_project container clusters get-credentials --region=europe-west1-b kflow1
Fetching cluster endpoint and auth data.
ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=404, message=Not found: projects/my_project/zones/europe-west1-b/clusters/kflow1.
No cluster named 'kflow1' in my_project.
Makefile:62: recipe for target 'create-ctxt' failed
make: *** [create-ctxt] Error 1

```

@melihsqsp
Please, did you try to create a cluster with gcloud ? did it work as expected ? 

@jlewi,
I don't know if it is important, but in the Makefile, I see :
```
# The URL you want to fetch manifests from
MANIFESTS_URL=https://github.com/kubeflow/manifests.git/gcp/v2/management@1f948ed
```
Is it the right commit ?

In the Makefile line 82 (hydrate-kcc), I also see this instruction 
`kubectl --context=$(MGMTCTXT) apply -f .build/cnrm-install-system/~g_v1_namespace_cnrm-system.yaml`
Looks strange to me because the subdirectory cnrm-install-system doesn't exist. And I see no file ~g_v1_namespace_cnrm-system.yaml

**Comment by Bobgy** [comment]
/assign @jlewi @Bobgy 
Looks like an urgent issue, I'll try to reproduce

**Comment by Bobgy** [comment]
@jal06 sorry for the late reply, your issue seems to be different.
Your management cluster name is `kfmgmnt`, right?
but when running `make create-ctxt`, it is looking for
> No cluster named 'kflow1'

So it seems your configuration for the management cluster's name somehow went wrong, can you double check?

**Comment by jal06** [comment]
@Bobgy, you are right. 
The documentation was a little bit confusing for me, and I did some mistakes when setting the configuration.

I created a new issue [142](https://github.com/kubeflow/gcp-blueprints/issues/142) for suggesting some clarification in the documentation. I hope it makes sense and will help others

**Comment by melihsqsp** [comment]
@Bobgy I still see this error.  Output to `make apply` gives me this
```
Flag --project has been deprecated, GCE project flag is unused and deprecated
W1109 15:00:57.257053   69876 warning.go:14] manifest is using some deprecated features; please run vet for details
I1109 15:00:57.257516   69876 main.go:230] reconcile serviceusage.cnrm.cloud.google.com/Service container.googleapis.com
I1109 15:00:59.071871   69876 main.go:230] reconcile container.cnrm.cloud.google.com/ContainerCluster kubeflow-manage
creating gke cluster: done
I1109 15:31:00.563315   69876 main.go:230] reconcile container.cnrm.cloud.google.com/ContainerNodePool kubeflow-manage-pool
W1109 15:31:01.322535   69876 nodepool.go:441] unsupported change: {Path:Config.WorkloadMetadataConfig.Mode Actual:GKE_METADATA Expected:}
```
The outcome is that I see the nodepool `kubeflow-management-pool` being created but no nodes and the subsequent steps can't be completed. What is causing this and is there a workaround?

**Comment by melihsqsp** [comment]
@jal06 I see a similar issue where the output to `make create-ctxt` says `No cluster named 'kubeflow-instance' in kubeflow-corp-001.` with the kubeflow instance name and not the management cluster name. In the Makefile there are 2 sets of variables to set one for management, one for instance. I assigned different names to each. Where is the problem?

**Comment by jal06** [comment]
@melihsqsp  if you want to install Kubeflow using gcp-blueprint, there are 2 steps.

The 1rst step is described in this page  [https://www.kubeflow.org/docs/gke/deploy/management-setup/](https://www.kubeflow.org/docs/gke/deploy/management-setup/)  and is for deploying the management cluster. In this 1rst step, you must set the name of the management cluster in those 2 variables (`./instance name NAME` and `./upstream/management name NAME`) and generally speaking, all the variables here refer to the management cluster. For example, you can `set kpt cfg set ./instance name MGMNT` and `kpt cfg set ./upstream/management name MGMNT` if you want to name your management cluster MGMNT

The 2nd step is described in this page [https://www.kubeflow.org/docs/gke/deploy/deploy-cli/](https://www.kubeflow.org/docs/gke/deploy/deploy-cli/) and is for deploying the Kubeflow cluster. In this second step, there is another Makefile in which you will have to set some variables. One of those variables is the name of the Kubeflow cluster, which is not described in the documentation but you can see it in the 2nd Makefilehere : [https://github.com/kubeflow/gcp-blueprints/blob/master/kubeflow/Makefile](https://github.com/kubeflow/gcp-blueprints/blob/master/kubeflow/Makefile)

Hope that helps.

**Comment by melihsqsp** [comment]
@jal06 I am on the first step. I modified the Makefile so it has this:
``` 
kpt cfg set ./instance name kubeflow-manage
...
kpt cfg set ./upstream/management name kubeflow-manage
```
followed by `make set-values` , `make apply` which outputs:
```
Flag --project has been deprecated, GCE project flag is unused and deprecated
W1109 16:52:35.401295   90112 warning.go:14] manifest is using some deprecated features; please run vet for details
I1109 16:52:35.402014   90112 main.go:230] reconcile serviceusage.cnrm.cloud.google.com/Service container.googleapis.com
I1109 16:52:37.345631   90112 main.go:230] reconcile container.cnrm.cloud.google.com/ContainerCluster kubeflow-manage
W1109 16:52:38.350037   90112 cluster.go:613] cluster master version is not set for cluster projects/kubeflow-corp-001/locations/us-east1-c/clusters/kubeflow-manage
W1109 16:52:38.350082   90112 cluster.go:707] unsupported change: {Path:ExpireTime Actual:2020-11-23T20:28:59+00:00 Expected:}
W1109 16:52:38.350096   90112 cluster.go:707] unsupported change: {Path:WorkloadIdentityConfig.WorkloadPool Actual:kubeflow-corp-001.svc.id.goog Expected:}
I1109 16:52:39.974991   90112 main.go:230] reconcile container.cnrm.cloud.google.com/ContainerNodePool kubeflow-manage-pool
W1109 16:52:40.823523   90112 nodepool.go:441] unsupported change: {Path:Config.WorkloadMetadataConfig.Mode Actual:GKE_METADATA Expected:}
Reconciliation completed successfully
```
make create-ctxt
```
+ echo Checking if context kubeflow-manage exists
Checking if context kubeflow-manage exists
+ kubectl config use-context kubeflow-manage
error: no context exists with the name: "kubeflow-manage"
+ RESULT=1
+ '[' 1 -eq 0 ']'
+ set -ex
+ gcloud --project=kubeflow-corp-001 container clusters get-credentials --region=us-east1-c kubeflow-manage
Fetching cluster endpoint and auth data.
WARNING: cluster kubeflow-manage is not running. The kubernetes API may not be available.
kubeconfig entry generated for kubeflow-manage.
++ kubectl config current-context
+ kubectl config rename-context gke_kubeflow-corp-001_us-east1-c_kubeflow-manage kubeflow-manage
Context "gke_kubeflow-corp-001_us-east1-c_kubeflow-manage" renamed to "kubeflow-manage".
+ kubectl config set-context --current --namespace=cnrm-system
```
make apply-kcc
```
W1109 16:55:31.681380   90692 warning.go:14] manifest is using some deprecated features; please run vet for details
I1109 16:55:31.682146   90692 main.go:230] reconcile serviceusage.cnrm.cloud.google.com/Service cloudresourcemanager.googleapis.com
Reconciliation completed successfully
anthoscli apply -f .build/cnrm-install-iam
W1109 16:55:33.487959   90716 warning.go:14] manifest is using some deprecated features; please run vet for details
I1109 16:55:33.488087   90716 main.go:230] reconcile iam.cnrm.cloud.google.com/IAMServiceAccount kubeflow-manage-cnrm-system
I1109 16:55:34.646506   90716 main.go:230] reconcile iam.cnrm.cloud.google.com/IAMPolicy kubeflow-manage-cnrm-system-wi
I1109 16:55:35.648698   90716 iam_policy.go:106] policy matches expected for projects/kubeflow-corp-001/serviceAccounts/kubeflow-manage-cnrm-system@kubeflow-corp-001.iam.gserviceaccount.com
Reconciliation completed successfully
kubectl --context=kubeflow-manage apply -f .build/cnrm-install-system/~g_v1_namespace_cnrm-system.yaml
error: unable to recognize ".build/cnrm-install-system/~g_v1_namespace_cnrm-system.yaml": Get https://34.73.34.206/api?timeout=32s: dial tcp 34.73.34.206:443: i/o timeout
make: *** [apply-kcc] Error 1
```

**Comment by jal06** [comment]
@melihsqsp it looks that the Makefiles were updated a few days ago.
My answer above is related to the old version of the Makefile
I didn't try the new version

**Comment by jal06** [comment]
@melihsqsp , please could you show all the values you set in your Makefile (instance and upstream name, location, ...)?

**Comment by melihsqsp** [comment]
Section of the Makefile
```
# Directory where manifests should be fetched to
MANIFESTS_DIR=./upstream/management

INSTANCE_DIR=./instance


#***********************************************************************************************************************
# Edit this section to set the values specific to your deployment

.PHONY: set-values
set-values:
        kpt cfg set ./instance name kubeflow-manage
        kpt cfg set ./instance location us-east1-c
        kpt cfg set ./instance gcloud.core.project kubeflow-corp-001

        kpt cfg set ./upstream/management name kubeflow-manage
        kpt cfg set ./upstream/management location us-east1-c
        kpt cfg set ./upstream/management gcloud.core.project kubeflow-corp-001

```

**Comment by jal06** [comment]
I see no problem in your Makefile. It sounds good to me.
It's a timeout, so maybe it's a network issue ?

Just for information, here is the content of .build/cnrm-install-system/~g_v1_namespace_cnrm-system.yaml 
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cnrm.cloud.google.com/version: 1.15.1
  labels:
    cnrm.cloud.google.com/system: "true"
  name: cnrm-system
```

Do you have the same content in this file ?

It looks strange to me that you still get this warning  about GKE_METADATA
W1109 16:52:40.823523   90112 nodepool.go:441] unsupported change: {Path:Config.WorkloadMetadataConfig.Mode Actual:GKE_METADATA Expected:}
Maybe you need to delete the management cluster and try to create it again ?

**Comment by melihsqsp** [comment]
yes the content of the crnm file is identical to what I have. I am also thinking the warning might be the reason
```
W1109 16:52:40.823523 90112 nodepool.go:441] unsupported change: {Path:Config.WorkloadMetadataConfig.Mode Actual:GKE_METADATA Expected:}
```
When I look under the cluster kubeflow-manage in the console I see a red exclamation mark next to it. There is a nodepool, but under the nodepool/nodes there is nothing listed. I am thinking no nodes were created during the `make apply` and when something is trying to access it later it gives that timeout error. Do you see nodes under the management cluster, I'd imaging there should be ?

**Comment by jal06** [comment]
@melihsqsp  Yes, there is 1 node pool with only 1 node (n1-standard-4) and the status is green.

I remember that the nodepool was red when I got the warning about GKE-METADATA. 
Then, I deleted the management cluster, and I created it again from scratch changing the name of the management cluster, and setting correctly the variables in the Makefile ...  and the management cluster was  created successfully (without the warning about GKE_METADATA) . 
Maybe I am wrong, but my guess is that the cause of the warning about GKE_METADATA is that I didn't set the variables correctly.
Creating a new management cluster using a different name, and setting correctly the variables solved my problem

**Comment by jal06** [comment]
@melihsqsp  I forgot 1 point 

The 1rst time I got the error about GKE_METADATA, my $PATH was pointing to an old version of istioctl.

The 2nd time I tried (successfully) to install the management cluster, I followed the instructions in the chapter 'Prepare the installation of Anthos Service Mesh' in this documentation before : `https://cloud.google.com/service-mesh/docs/archive/1.4/docs/gke-install-new-cluster#preparing_to_install_anthos_service_mesh` before installing the management cluster
You must execute only the installation of anthoscli and istioctl, which are binaries from google site


Here is the istioctl I have now :
`./istioctl version`
```
client version: 1.4.10-asm.18
galley version: 1.4.7-asm.0
galley version: 1.4.7-asm.0
ingressgateway version: 1.4.7-asm.0
ingressgateway version: 1.4.7-asm.0
nodeagent version: 
nodeagent version: 
nodeagent version: 
pilot version: 1.4.7-asm.0
pilot version: 1.4.7-asm.0
sidecar-injector version: 1.4.7-asm.0
sidecar-injector version: 1.4.7-asm.0
```

You can see that it is a version which works with Anthos Service Mesh
Maybe you could check which version of istioctl you are using.
It looks that now the installation guide has been updated and I don't know which version of istioctl must be used.

Hope that helps.

**Comment by nico-kuzak** [comment]
> @jal06 I am on the first step. I modified the Makefile so it has this:
> 
> ```
> kpt cfg set ./instance name kubeflow-manage
> ...
> kpt cfg set ./upstream/management name kubeflow-manage
> ```
> 
> followed by `make set-values` , `make apply` which outputs:
> 
> ```
> Flag --project has been deprecated, GCE project flag is unused and deprecated
> W1109 16:52:35.401295   90112 warning.go:14] manifest is using some deprecated features; please run vet for details
> I1109 16:52:35.402014   90112 main.go:230] reconcile serviceusage.cnrm.cloud.google.com/Service container.googleapis.com
> I1109 16:52:37.345631   90112 main.go:230] reconcile container.cnrm.cloud.google.com/ContainerCluster kubeflow-manage
> W1109 16:52:38.350037   90112 cluster.go:613] cluster master version is not set for cluster projects/kubeflow-corp-001/locations/us-east1-c/clusters/kubeflow-manage
> W1109 16:52:38.350082   90112 cluster.go:707] unsupported change: {Path:ExpireTime Actual:2020-11-23T20:28:59+00:00 Expected:}
> W1109 16:52:38.350096   90112 cluster.go:707] unsupported change: {Path:WorkloadIdentityConfig.WorkloadPool Actual:kubeflow-corp-001.svc.id.goog Expected:}
> I1109 16:52:39.974991   90112 main.go:230] reconcile container.cnrm.cloud.google.com/ContainerNodePool kubeflow-manage-pool
> W1109 16:52:40.823523   90112 nodepool.go:441] unsupported change: {Path:Config.WorkloadMetadataConfig.Mode Actual:GKE_METADATA Expected:}
> Reconciliation completed successfully
> ```
> 
> make create-ctxt
> 
> ```
> + echo Checking if context kubeflow-manage exists
> Checking if context kubeflow-manage exists
> + kubectl config use-context kubeflow-manage
> error: no context exists with the name: "kubeflow-manage"
> + RESULT=1
> + '[' 1 -eq 0 ']'
> + set -ex
> + gcloud --project=kubeflow-corp-001 container clusters get-credentials --region=us-east1-c kubeflow-manage
> Fetching cluster endpoint and auth data.
> WARNING: cluster kubeflow-manage is not running. The kubernetes API may not be available.
> kubeconfig entry generated for kubeflow-manage.
> ++ kubectl config current-context
> + kubectl config rename-context gke_kubeflow-corp-001_us-east1-c_kubeflow-manage kubeflow-manage
> Context "gke_kubeflow-corp-001_us-east1-c_kubeflow-manage" renamed to "kubeflow-manage".
> + kubectl config set-context --current --namespace=cnrm-system
> ```
> 
> make apply-kcc
> 
> ```
> W1109 16:55:31.681380   90692 warning.go:14] manifest is using some deprecated features; please run vet for details
> I1109 16:55:31.682146   90692 main.go:230] reconcile serviceusage.cnrm.cloud.google.com/Service cloudresourcemanager.googleapis.com
> Reconciliation completed successfully
> anthoscli apply -f .build/cnrm-install-iam
> W1109 16:55:33.487959   90716 warning.go:14] manifest is using some deprecated features; please run vet for details
> I1109 16:55:33.488087   90716 main.go:230] reconcile iam.cnrm.cloud.google.com/IAMServiceAccount kubeflow-manage-cnrm-system
> I1109 16:55:34.646506   90716 main.go:230] reconcile iam.cnrm.cloud.google.com/IAMPolicy kubeflow-manage-cnrm-system-wi
> I1109 16:55:35.648698   90716 iam_policy.go:106] policy matches expected for projects/kubeflow-corp-001/serviceAccounts/kubeflow-manage-cnrm-system@kubeflow-corp-001.iam.gserviceaccount.com
> Reconciliation completed successfully
> kubectl --context=kubeflow-manage apply -f .build/cnrm-install-system/~g_v1_namespace_cnrm-system.yaml
> error: unable to recognize ".build/cnrm-install-system/~g_v1_namespace_cnrm-system.yaml": Get https://34.73.34.206/api?timeout=32s: dial tcp 34.73.34.206:443: i/o timeout
> make: *** [apply-kcc] Error 1
> ```

Did you figure out the error stemming from make apply-kcc?

```
kubectl --context=kubeflow-manage apply -f .build/cnrm-install-system/~g_v1_namespace_cnrm-system.yaml
error: unable to recognize ".build/cnrm-install-system/~g_v1_namespace_cnrm-system.yaml": Get https://34.73.34.206/api?timeout=32s: dial tcp 34.73.34.206:443: i/o timeout
make: *** [apply-kcc] Error 1
```

For me, it just says that the file does not exist.

**Comment by Bobgy** [comment]
@melihsqsp I'd suggest deleting this cluster via gcloud or cloud console and try again.

For comparison, you can also create the cluster via gcloud and comment out related steps in the makefile. The only requirement for this cluster is to enable workload identity

**Comment by melihsqsp** [comment]
I found that under IAM `Compute Engine default service account` was set to disabled. After enabling it deleting the cluster and rerunning installation I can see the management cluster. This was a new project so it might be a default setting. It might make sense to make a note of this issue in case other people also run into it.

**Comment by melihsqsp** [comment]
Now, after I run `make apply` as here https://www.kubeflow.org/docs/gke/deploy/deploy-cli/#deploy-kubeflow  I see message 
```
# Apply management resources
...
kubectl --context=kubeflowmgt apply -f ./.build/gcp_config
computeaddress.compute.cnrm.cloud.google.com/kubeflow-1.1.0-ip unchanged
computedisk.compute.cnrm.cloud.google.com/kubeflow-1.1.0-storage-artifact-store unchanged
computedisk.compute.cnrm.cloud.google.com/kubeflow-1.1.0-storage-metadata-store unchanged
containercluster.container.cnrm.cloud.google.com/kubeflow-1.1.0 configured
....

kubectl --context=kubeflowmgt wait --for=condition=Ready --timeout=600s  containercluster kubeflow-1.1.0
error: timed out waiting for the condition on containerclusters/kubeflow-1.1.0
make: *** [wait-gcp] Error 1
```
It is failing on something with containercluster

**Comment by Bobgy** [comment]
@melihsqsp you can find out why in https://github.com/kubeflow/gcp-blueprints/issues/154

**Comment by Bobgy** [comment]
the problem has been solved and we will make this documentation and validation better in #154
