### ISSUE TITLE
ASM Mesh Id should  be - proj-${PROJECTNUMBER}

### ISSUE THREAD

**Issue by jlewi** [kubeflow/gcp-blueprints#117]
According to the latest ASM instructions
https://cloud.google.com/service-mesh/docs/gke-install-asm#validating_the_installation

the mesh id should be "proj-${PROJECTNUMBER}" it looks like this changed in a recent release.

In my case no services showed up in the ASM dashboard until I

* Upgraded to ASM 1.4.10 from 1.4.7
* Set the mesh id to "proj-${PROJECTNUMBER}"

I'm not sure which or both of these actually fixed my problem.

**Comment by Bobgy** [comment]
Let me send a PR for the fix, I tried to use ASM dashboard but couldn't find anything useful there. It would be a waste of ASM if the dashboard doesn't work.

**Comment by jlewi** [comment]
I also needed to register my cluster with Anthos.
