### ISSUE TITLE
Tag a v1.1.0 release

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/gcp-blueprints#118]
Hi @jlewi, we haven't been tagging a v1.1.0 release tag and instructions on https://www.kubeflow.org/docs/gke/deploy/management-setup/ are still pointing to master.

**Comment by jlewi** [comment]
Thanks @Bobgy I sent you #122 with some mixing fixes to the blueprint cluster that was preventing us from switching to the management cluster to the 1.1 branch.

I'm on the fence about whether our docs should refer to a branch or a specific/commit tag. WDYT?

**Comment by Bobgy** [comment]
I think we should always be referring to a commit tag, that's the only way to make user errors reproducible.

What concerns do you have? Do you worry management cluster might not change much, but we may need to update its version in doc each time?

**Comment by Bobgy** [comment]
Comparing to tag vs branch, I was actually more confused by release branch process in gcp blueprints repo.
I don't think we are going to work on any PRs not meant to be fixing issues for KF 1.1 right now, but we have to cherry pick every PR (a lot of manual effort).

I'd want to propose a lazy procedure for cutting release branch:
```
we cut a release branch when we find the first merged PR we don't want to release.
```

**Comment by Bobgy** [comment]
Was the reason for 1.1 branch as a way to release? e.g. we document to let users to use the branch.

Then if we switch to tag for release, we can save the cherrypick process of maintaining two branches for now.

**Comment by jlewi** [comment]
@Bobgy The lazy approach you mention sounds like a great idea. I only cut a branch because I was replicating what we already do for the kubeflow repos.

**Comment by Bobgy** [comment]
Great, I'll see how we can switch the process, so far it looks like master and v1.1 is almost the same, with really minor diffs.

I guess one thing we need to handle is, we need to change autodeploy process to use the same branch, but parameterize where manifests should be get, one should use master manifests and one should use v1.1.0 branch.

Another question is: how do we tag a release for a repo? Sounds like I need more permission to the repo.
Would https://github.com/kubeflow/internal-acls/pull/311 address this?

**Comment by jlewi** [comment]
kubeflow/internal-acls#311 should address this; although you could also create a specific team with permissions on the repo.

> I guess one thing we need to handle is, we need to change autodeploy process to use the same branch, but parameterize where manifests should be get, one should use master manifests and one should use v1.1.0 branch.

Yeah I didn't think of that. Would it make sense to still cut branches for the v1.X.Y releases so that we can change the manifests on that release branch to point to the correct manifests release?

We could just cut a new release branch off the latest master for each v1.X.Y release. So we don't need to cherry-picks.

Alternatively, you could just merge master into the v1.X-branch before cutting adding the tag v1.X.Y.

I guess its just a matter of what you prefer

1. Merging in all changes on master
1. Cutting from master and updating the manifests version

**Comment by Bobgy** [comment]
> We could just cut a new release branch off the latest master for each v1.X.Y release. So we don't need to cherry-picks.
> Alternatively, you could just merge master into the v1.X-branch before cutting adding the tag v1.X.Y.

Great idea, sounds like both works, let me try merging master first because it's less intrusive (no need to delete the existing v1.1 branch).

**Comment by Bobgy** [comment]
I'll cut a 1.1.0 release tag just to archive current status.

**Comment by Bobgy** [comment]
Tagged https://github.com/kubeflow/gcp-blueprints/releases/tag/v1.1.0

**Comment by Bobgy** [comment]
@jlewi I just realized management cluster in gcp-blueprints is pointing to manifests master. When do you think we can pin a release tag on manifest repo for v1.1.1 or v1.1.1-rc.1? How do we usually coordinate work across kubeflow?

I'll pin management cluster to v1.1-branch in manifest first.

**Comment by jlewi** [comment]
@Bobgy SGTM thanks

**Comment by Bobgy** [comment]
Pinned 1.1.0 and updated documentation
