### ISSUE TITLE
8.18 - Presubmit tests failing - KCC stuck at creating clusters

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/gcp-blueprints#128]
I found presubmit tests are failing completely:
e.g. https://github.com/kubeflow/gcp-blueprints/pull/127

I did the following things to troubleshoot:
* I took a look at the tekton task, it failed waiting for the containercluster to be provisioned.
* I started taking a look at the kubeflow-ci-management cluster.
* The containercluster doesn't have a status field, it seems to indicate something went wrong with KCC controller.
* I looked at KCC controller and find a bunch of errors saying IAMPolicy referenced resource doesn't not exist.
* I listed all IAMPolicies:
```
NAME                                            AGE
kf-vbp-0626-0e4-admin-workload-identity-users   52d
kf-vbp-0626-0e4-user-workload-identity-users    52d
kf-vbp-0627-c30-admin-workload-identity-users   51d
kf-vbp-0627-c30-user-workload-identity-users    51d
kf-vbp-0627-d77-admin-workload-identity-users   51d
kf-vbp-0627-d77-user-workload-identity-users    51d
kf-vbp-0628-2d0-admin-workload-identity-users   50d
kf-vbp-0628-2d0-user-workload-identity-users    50d
kf-vbp-0628-6c8-admin-workload-identity-users   51d
kf-vbp-0628-6c8-user-workload-identity-users    51d
kf-vbp-0628-b46-admin-workload-identity-users   50d
kf-vbp-0628-b46-user-workload-identity-users    50d
kf-vbp-0628-e73-admin-workload-identity-users   51d
kf-vbp-0628-e73-user-workload-identity-users    51d
kf-vbp-0629-3ed-admin-workload-identity-users   49d
kf-vbp-0629-3ed-user-workload-identity-users    49d
kf-vbp-0629-3f5-admin-workload-identity-users   49d
kf-vbp-0629-3f5-user-workload-identity-users    49d
kf-vbp-0629-571-admin-workload-identity-users   50d
kf-vbp-0629-571-user-workload-identity-users    50d
kf-vbp-0629-be4-admin-workload-identity-users   49d
kf-vbp-0629-be4-user-workload-identity-users    49d
kf-vbp-0630-31d-admin-workload-identity-users   48d
kf-vbp-0630-31d-user-workload-identity-users    48d
kf-vbp-0630-56d-admin-workload-identity-users   48d
kf-vbp-0630-56d-user-workload-identity-users    48d
kf-vbp-0630-8f5-admin-workload-identity-users   48d
kf-vbp-0630-8f5-user-workload-identity-users    48d
kf-vbp-0630-dcc-admin-workload-identity-users   49d
kf-vbp-0630-dcc-user-workload-identity-users    49d
kf-vbp-0701-947-admin-workload-identity-users   47d
kf-vbp-0701-947-user-workload-identity-users    47d
kf-vbp-0701-a8a-admin-workload-identity-users   47d
kf-vbp-0701-a8a-user-workload-identity-users    47d
kf-vbp-0701-ab4-admin-workload-identity-users   48d
kf-vbp-0701-ab4-user-workload-identity-users    48d
kf-vbp-0702-583-admin-workload-identity-users   47d
kf-vbp-0702-583-user-workload-identity-users    47d
kf-vbp-0702-847-admin-workload-identity-users   47d
kf-vbp-0702-847-user-workload-identity-users    47d
kf-vbp-0702-8da-admin-workload-identity-users   46d
kf-vbp-0702-8da-user-workload-identity-users    46d
kf-vbp-0702-c8c-admin-workload-identity-users   46d
kf-vbp-0702-c8c-user-workload-identity-users    46d
kf-vbp-0703-7f5-admin-workload-identity-users   45d
kf-vbp-0703-7f5-user-workload-identity-users    45d
kf-vbp-0703-e44-admin-workload-identity-users   45d
kf-vbp-0703-e44-user-workload-identity-users    45d
kf-vbp-0704-721-admin-workload-identity-users   44d
kf-vbp-0704-721-user-workload-identity-users    44d
kf-vbp-0704-82a-admin-workload-identity-users   44d
kf-vbp-0704-82a-user-workload-identity-users    44d
kf-vbp-0704-9c6-admin-workload-identity-users   45d
kf-vbp-0704-9c6-user-workload-identity-users    45d
kf-vbp-0704-a55-admin-workload-identity-users   45d
kf-vbp-0704-a55-user-workload-identity-users    45d
kf-vbp-0705-3b9-admin-workload-identity-users   43d
kf-vbp-0705-3b9-user-workload-identity-users    43d
kf-vbp-0705-c34-admin-workload-identity-users   43d
kf-vbp-0705-c34-user-workload-identity-users    43d
kf-vbp-0705-e35-admin-workload-identity-users   44d
kf-vbp-0705-e35-user-workload-identity-users    44d
kf-vbp-0706-fd3-admin-workload-identity-users   43d
kf-vbp-0706-fd3-user-workload-identity-users    43d
```
Looks like they are all outdated.

Each IAMPolicy has spec like
```
status:
  conditions:
  - lastTransitionTime: "2020-08-18T08:13:51Z"
    message: 'error getting resource config for referenced resource: the referenced
      resource does not exist'
    status: "False"
    type: Ready
```

How do we GC them?

**Comment by Bobgy** [comment]
/assign @jlewi 
Do you know the answer to above question?

**Comment by Bobgy** [comment]
For quick workaround, I cleaned up all IAMPolicies to see if it fixes test failures.

**Comment by Bobgy** [comment]
Then we'd probably need to upgrade the KCC install

**Comment by Bobgy** [comment]
I found an internal issue tracking the KCC bug, asking if there are any updates.

**Comment by Bobgy** [comment]
Despite above mentioned GC problem, it seems after I restart KCC controller, ContainerCluster is created successfully now, although reconcile cycle seems to be slower than usual. I'm suspecting the slowness is caused by above GC problem.

**Comment by Bobgy** [comment]
Hmmm, restarting the controller doesn't solve it forever. It only reconciles for a while, it still fails to reconcile a containercluster to ready: true.

```
status:
  conditions:
  - lastTransitionTime: "2020-08-18T08:04:40Z"
    message: Update in progress
    reason: Updating
    status: "False"
    type: Ready
```

Although, I can see on cloud console, the cluster is already ready.

**Comment by jlewi** [comment]
@Bobgy Thanks for digging into this. I think I hit similar issues to this in the past. Is their resource contention going on?

i.e all of the IAMPolicyMembers are trying to update the IAMPolicy and this leads to contention because IAMPOlicy can only be updated atomically?

Is the GC problem in our logic or in KCC? It looks like we have very old IAMPolicyMembers e.g.

```
kf-vbp-0626-0e4-admin-workload-identity-users   52d
kf-vbp-0626-0e4-user-workload-identity-users    52d
kf-vbp-0627-c30-admin-workload-identity-users   51d
kf-vbp-0627-c30-user-workload-identity-users    51d
```

These look like past tests that should have been deleted a long time ago. Are we not cleaning those up successfully


nit: It would be good to update the issue title to be more descriptive now that you have made progress root causing it

**Comment by Bobgy** [comment]
@jlewi I got a reply from the internal bug mentioning it might be a KCC scaling problem, we can upgrade once they get their latest release out.

Strangely, did you do anything or what happened that the stuck iam policies are cleaned up today. I'm rerunning tests to see if they work now.

**Comment by Bobgy** [comment]
Something strange in test failure today is that, tekton seems to get problems: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_gcp-blueprints/127/kubeflow-gcp-blueprints-presubmit/1295965123369766912/.

The tekton task loads forever: https://kf-ci-v1.endpoints.kubeflow-ci.cloud.goog/tekton/#/namespaces/auto-deploy/pipelineruns/deploy-kf-master-hjm74

and fails with cannot find it

**Comment by jlewi** [comment]
What is the output of `kubectl describe` for the pipelineruns and taskruns?

**Comment by Bobgy** [comment]
I didn't have time clean up the resources, but looks like presubmit tests have been back to normal.

Though, it's still a valid problem how we can GC tekton resources.
Tekton community has an issue https://github.com/tektoncd/experimental/issues/479 tracking this.

**Comment by Bobgy** [comment]
I think we need at least a bash script to clean up old tekton resources on demand.

**Comment by Bobgy** [comment]
We can track the GC problem in https://github.com/kubeflow/testing/issues/750.

Just double check @jlewi, did you do anything to fix the presubmit tests? or it just recovered by itself?
