### ISSUE TITLE
unable to recognize "./.build/istio/Base/Base.yaml": Get https://x.x.x.x/api?timeout=32s

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/gcp-blueprints#132]
get the following error message when `apply-asm` step in kubeflow/Makefile
```
kubectl --context=dsp-kubeflow apply --recursive=true -f ./.build/istio/Base/Base.yaml
unable to recognize "./.build/istio/Base/Base.yaml": Get https://x.x.x.x/api?timeout=32s: dial tcp x.x.x.x:443: i/
```

reported in https://kubeflow.slack.com/archives/C7REE0EHK/p1599122036065700

The error message just means kubectl failed to reach the kubernete api server, but the most common way for getting this problem is that:
1. deploy a kubeflow instance
2. sth fails, so delete the kubeflow instance
3. fix some issues and redeploy a kubeflow instance with the same KF_NAME

Now, there's already a kubectl context with the same cluster name, so https://github.com/kubeflow/gcp-blueprints/blob/395902ee5f8069f3d0ed5c50a51f9aee62ce0c40/kubeflow/hack/create_context.sh#L19-L22
The create-ctxt.sh script won't create a new context instead, and the kubectl context will point to the deleted cluster deployed in step 1.

**Comment by Bobgy** [comment]
the workaround is `kubectl config delete-context $KF_NAME`, so that when you run `make apply` again, it will create the new context for you.

**Comment by Bobgy** [comment]
/cc @jlewi 
I'm thinking maybe we can just always refetch the kubectl context, it doesn't hurt in other ways, but it solves this purpose.

**Comment by jlewi** [comment]
The error looks like the IP address is wrong. I'm guessing the recreated the cluster and the IP address changed?
Does it really make sense to recreate the context on every call? That seems like an unnecessary call to gcloud container clusters get-credentials which adds a bit of latency.

Maybe we could just document the error in the troubleshooting guide and tell people to recreate the context?

**Comment by Bobgy** [comment]
Fixed by https://github.com/kubeflow/gcp-blueprints/pull/134.
