### ISSUE TITLE
Usability improvement : better naming of variable

### ISSUE THREAD

**Issue by jal06** [kubeflow/gcp-blueprints#142]
When instaling Kubeflow in GCP, we must now create 2 K8S clusters 
- 1 management cluster
- 1 Kubeflow cluster 

During the installation, we use the same variable NAME for those 2 clusters. IMHO, it's a little bit confusing and it could help to name those clusters with different names in the documentation and in Makefile

See documentation and Makefile 
- for management cluster : [documentation](https://www.kubeflow.org/docs/gke/deploy/management-setup/) and [Makefile](https://github.com/kubeflow/gcp-blueprints/blob/master/management/Makefile)
- for Kubeflow cluster : [documentation](https://www.kubeflow.org/docs/gke/deploy/deploy-cli/). For  [Makefile](https://github.com/kubeflow/gcp-blueprints/blob/master/kubeflow/Makefile), it already sounds good.

For example, when setting up the management cluster, it would help users to name the management cluster MGMNT_NAME (or maybe CNRM_NAME) instead of NAME. And in the page [Deploy using kubectl and kpt](https://www.kubeflow.org/docs/gke/deploy/deploy-cli/), add some details about the variable <YOUR_KF_NAME> in the Makefile.

**Comment by Bobgy** [comment]
Thank you @jal06, I think these are great suggestions!

**Comment by Bobgy** [comment]
Taking upgrade experience into consideration, I don't want to change the variable name.
But I think we can add documentation to further clarify at least.

**Comment by jal06** [comment]
OK, that makes sense.

**Comment by Bobgy** [comment]
I took a stab at https://github.com/kubeflow/website/pull/2372.
the `kpt setter` names need to be reserved, but we can change env var names in the documentation.
I've updated to use `${KF_NAME}` and `${MGMT_NAME}` consistently for the two different purposes. I believe this should make it a lot clearer.
