### ISSUE TITLE
Kubeflow Makefile should validate the value of `$(NAME)`

### ISSUE THREAD

**Issue by chensun** [kubeflow/gcp-blueprints#154]
I set [`$(NAME)`](https://github.com/kubeflow/gcp-blueprints/blob/36e6d0ad28bb85f83fdbee4c18229b18e56e98c2/kubeflow/Makefile#L37) with value `kf1.1`, which turned out to be an invalid name, but there was no complaint from `make set-values`.

Later running `make apply` failed with error:
```
kubectl --context=kf-cluster-201112 wait --for=condition=Ready --timeout=600s  containercluster kf1.1
error: timed out waiting for the condition on containerclusters/kf1.1
```

Trouble shooting with `kubectl describe containercluster --context $MANAGEMENT -n $PROJECT kf1.1` revealed:
```
Events:
  Type     Reason              Age                 From                         Message
  ----     ------              ----                ----                         -------
  Warning  DependencyNotReady  11m (x10 over 66m)  containercluster-controller  reference IAMServiceAccount chesu-dev/kf1.1-vm is not ready
```

Next, `kubectl describe iamserviceaccount --context $MANAGEMENT -n $PROJECT kf1.1-vm` revealed:
```
Events:
  Type     Reason        Age                 From                          Message
  ----     ------        ----                ----                          -------
  Normal   Updating      13m (x21 over 69m)  iamserviceaccount-controller  Update in progress
  Warning  UpdateFailed  13m (x21 over 69m)  iamserviceaccount-controller  Update call failed: error validating configuration: "account_id" ("kf1.1-vm") doesn't match regexp "^[a-z](?:[-a-z0-9]{4,28}[a-z0-9])$"
```

## Conclusion:

Given we expect three service accounts formed with this name:
- `NAME-admin`
- `NAME-user`
- `NAME-vm`

We need to validate its value to make sure that:
1. its length doesn't exceed 24.
1. it must start with [a-z] and contain only [-a-z0-9].

**Comment by Bobgy** [comment]
We added this in documentation, but it'll be ideal if we can add the regex check in the Makefile
