### ISSUE TITLE
[Discussion] UX for kpt cfg set both instance and upstream folders

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/gcp-blueprints#158]
Discussion thread: https://github.com/kubeflow/gcp-blueprints/pull/155/files#r523194024

Options:
1. Ask users call `kpt cfg set` for both `instance` and `upstream` folder for each variable
2. `instance/settings.yaml` stores dictionary of settings, and set upstream folder using it
3. `instance/Kptfile` stores kpt setters and set upstream folder using it

In Kubeflow 1.1, we used option 1.
Right now, we have migrated to option 3 based on discussion in #120 .

@chensun raised some concerns this is not very straightforward to users.

> Personally, I feel it's much easier to open a file and edit three places in comparison to running three commands. 
While I realize this `./instance/Kptfile` looks a bit complex, the `./instance/settings.yaml` existed in the early version looked very straightforward and easy to be edited directly. Why did we drop that file?

_Originally posted by @chensun in https://github.com/kubeflow/gcp-blueprints/pull/155#r523194024_

Arguments preferring option 3:
> I think using kpt consistently is preferable as this creates a consistent experience. 
Users can do `kpt cfg list-setters .` to see all of the setters and then set them appropriately. 
This is consistent with respect to how arbitrary kpt packages are managed.
e.g. if a user downloads some new kpt package the expectation would be they run list-setters to see what setters exist and then set them.
>
> In contrast settings.yaml was a non-standard, KF specific solution. So I think getting rid of that in favor of standardizing on Kpt is preferable.

_Originally posted by @jlewi in https://github.com/kubeflow/gcp-blueprints/pull/155#r523434109_

**Comment by Bobgy** [comment]
/cc @jlewi @chensun @subodh101 
Let's use this issue for further discussion, because this change is not included in scope of https://github.com/kubeflow/gcp-blueprints/pull/155

**Comment by Bobgy** [comment]
For goals of the UX, I agree with the following:
1. We do not want to hide `kpt` semantics or build an abstraction on top
2. We want to avoid asking users setting the same values twice

When we evaluate the goals, I feel like option 3 isn't fully achieving that either, because
reading our instructions, users would think they use `kpt cfg set` on instance folder to set something
and then something magically set all the values on the upstream folder (under the assumption they never looked into the Makefile).

Ideally, I think we want them to know that, they are just using `kpt cfg set` to configure both instance and upstream folder. The situation is that both folders have the same parameter set.

Hmmmm, can we do this instead?
Instructions:
```
kpt cfg set {./instance,./upstream} name NAME
kpt cfg set {./instance,./upstream} gcloud.core.project PROJECT
kpt cfg set {./instance,./upstream} location LOCATION
```

This sort of depends on bash syntax, but if we also introduce that
`kpt cfg set {./instance,./upstream} name NAME` is equivalent to `kpt cfg set ./instance name NAME && kpt cfg set ./upstream name NAME`. Maybe this is simpler than option 1-3 and doesn't hide anything from users.

**Comment by jlewi** [comment]
Is the long term solution here kpt support for subpackages?

I think this is still being designed see:
https://github.com/GoogleContainerTools/kpt/issues/1093

The blueprint basically consists of two sub-packages
* $(BLUEPRINT)/instance
* $(BLUEPRINT)/upstream

(Arguably these could/should be further subdivided).

I believe with sub packages you should be able to set values at the root level e.g.  

```
kpt cfg set $(BLUEPRINT) ....
```

And then have those values trickle down to the subpackages.

I believe this would meet the desired UX; eg.

* Users only set the values once
* Users get a native kpt experience
* Users values are preserved when the update the upstream packages

**Comment by Bobgy** [comment]
@jlewi sounds reasonable to me.

So, for a stop gap solution.
I'd propose the following:
Separate out a set-values.sh, it contains a loop over the two packages and let the user edit values.
The script will be called by Makefile before hydration.

This exposes kpt semantic, because users need to edit the script.
Also, this moves common user editions out of the Makefile, so it's easier to swap out the Makefile for upgrade.

**Comment by subodh101** [comment]
I think the process of setting `kpt cfg set` by commands and adding the `kpt cfg list-setters ./instance/` in the troubleshoot sounds good to me(Or even with a note in the docs itself).
It may be a little new at the start getting comfortable with `kpt cfg set`. However it is pretty straight forward from the docs. If a user wants to copy all commands somewhere, edit and then fire. That's his/her choice. Placing the same kpt values at two places in our code doesn't sound good to me.


```
▶ kpt cfg list-setters ./instance/
            NAME                        VALUE              SET BY   DESCRIPTION   COUNT  
  email                      EMAIL                                                2      
  gcloud.compute.zone        ZONE                                                 0      
  gcloud.core.project        PROJECT                                              6      
  gke.private                false                                                0      
  kustomize_manifests_path   ../../../upstream/manifests                          12     
  location                   LOCATION                                             0      
  log-firewalls              false                                                0      
  mgmt-ctxt                  MANAGEMENT-CTXT                                      0      
  name                       KUBEFLOW-NAME                                        9      
```

checking the values is a much better solution. We don't know yet what more variables can come in.

**Comment by Bobgy** [comment]
@subodh101 can you describe what the instructions would look like that seems ideal to you?

Does asking users to copy paste the following sound good?
```
for package in instance upstream/management
do
    kpt cfg set ${package} name ${NAME}
    kpt cfg set ${package} gcloud.core.project ${PROJECT}
    kpt cfg set ${package} location ${LOCATION}
done
```

Also, when they update upstream package, we won't automatically set values for the upstream package. If they run any command, they should find out an error message saying the upstream package has all values same as default, so they will know they need to set these values again.

**Comment by jlewi** [comment]
> So, for a stop gap solution.

Why do we need a stop gap beyond what exists today? Why not figure out what it should look like using sub-packages and then figure out how to migrate to that?

If we're going to invest in improving things should we think a bit longer term and revisit some other core design e.g

* Should we divide Kubeflow into multiple kpt packages; one per application?

   * Would this make Kubeflow more modular and move us in the direction of making it easier for users to select the applications they want?

* Does having instance and upstream directories make sense? Can it be improved?

   * The motivation here was to cleanly separate user defined patches/overlays to avoid 3-way merge conflicts when upgrading the packages

**Comment by Bobgy** [comment]
GoogleContainerTools/kpt#1093

The issue is still open. Has kpt supported that? I'll ask on the email thread about it. If kpt already supports that, then it totally makes sense to me.

**Comment by Bobgy** [comment]
> If we're going to invest in improving things should we think a bit longer term and revisit some other core design e.g
> 
> * Should we divide Kubeflow into multiple kpt packages; one per application?
> 
>    * Would this make Kubeflow more modular and move us in the direction of making it easier for users to select the applications they want?

Completely agree with this! I have been holding the exact opinion. If we can separate each application, ingress, istio ... while describing dependency of each, it will be much easier to use part of kubeflow on an existing cluster or swap out a core infra with user's preferred version.

For Kubeflow 1.2, I don't think I have time to tackle this though. I think it will be good trying to drive manifest WG towards this direction, so that we can build on top of them.

> * Does having instance and upstream directories make sense? Can it be improved?
> 
>    * The motivation here was to cleanly separate user defined patches/overlays to avoid 3-way merge conflicts when upgrading the packages

So far, I think the abstraction works well. E.g. for management cluster upgrade to kf 1.2, I was able to be compatible with existing instance folders.

**Comment by subodh101** [comment]
> @subodh101 can you describe what the instructions would look like that seems ideal to you?

The thought process behind removing `settings.yaml` was  https://en.wikipedia.org/wiki/Don%27t_repeat_yourself even if it is twice and keeping one source of truth.

> Does asking users to copy paste the following sound good?

Once they have set the variables and it is available in their version control.
Those values are not going away neither users are doing updates every day that this step needs special focus.
But now they will also have to copy a new file of `set-values.sh` to violate the principle.

Which is why the previous changes were much suitable from the coding standards as well as users' point of view.

**Comment by Bobgy** [comment]
@subodh101 
after user upgrades upstream package, we will `rm -rf upstream/management` and `kpt pkg get` again.
In this process, Kptfile values in the upstream package will be lost, so we need a mechanism to set it again either from `set-values.sh` or `instance/Kptfile`.

If we choose `set-values.sh`, user need to get the script as abstraction.
If we choose `instance/Kptfile`, we need to add some rules in the makefile that auto set the upstream, which is also some abstraction.

Comparing the two, I feel like `set-values.sh` shows users what's happening (when they edit the values). While adding rules that auto-set the upstream is hiding those from users (because they only set instance directly, setting values for upstream is completely hidden).

but anyway, if as jlewi said, kpt cfg set works for sub-packages, we should use that instead.

**Comment by Bobgy** [comment]
Nevermind, I've found that `kpt cfg set . name NAME -R` is doing the trick.
`-R` stands for
```
--recurse-subpackages   sets recursively in all the nested subpackages
```

**Comment by Bobgy** [comment]
Even if the parent folder doesn't have a `Kptfile`, the recursive set still works.

**Comment by Bobgy** [comment]
OK, I think we can go with telling users to
```
# this lists both instance and upstream package's setters
kpt cfg list-setters ./
```
and
```
# this sets values for all setters in all subpackages recursively
kpt cfg set . -R name NAME
```

**Comment by jlewi** [comment]
@Bobgy this is a nice find; I think what you are proposing is a nice improvement.

**Comment by Bobgy** [comment]
I was trying to also refactor kubeflow package, however I'm blocked by a kpt bug: https://github.com/GoogleContainerTools/kpt/issues/1230.

Somehow, I didn't successfully get the recurse subpackages feature working with kubeflow package

**Comment by Bobgy** [comment]
Before the upstream issue is resolved, I'd like to revert https://github.com/kubeflow/gcp-blueprints/pull/137 and https://github.com/kubeflow/gcp-blueprints/pull/135, so that users upgrading to Kubeflow 1.2 do not need to learn an unnecessary pattern change and get to learn again the `-R` flag once again in Kubeflow 1.3.

/cc @subodh101 
what do you think?

**Comment by jlewi** [comment]
@Bobgy do you hit GoogleContainerTools/kpt#1230 even if you don't pull the entire kubeflow/manifests repo?  I wonder if there are specific subdirs in kubeflow/manifests that are breaking things and which we don't need so if we just removed them we could work around the bug.
https://github.com/kubeflow/gcp-blueprints/blob/master/kubeflow/Makefile#L86

**Comment by Bobgy** [comment]
@jlewi You are right, management package works fine, so there should be sth in manifests that break it.

I don't think I will have time to break up the kubeflow package for 1.2 release, thus the current decision.

**Comment by Bobgy** [comment]
But what's strange is that, this issue doesn't happen immediately after I pull the whole package, it shows up after I remove a few problematic folders.

**Comment by jlewi** [comment]
Long term this problem might go away if we start having N `kpt pkg get` statements one fetching each application. This would make it easy to fetch packages regardless of where they are hosted.

**Comment by Bobgy** [comment]
Agree, I was hoping kpt could fix this issue before we reach that long term, it will take a while.

**Comment by zijianjoy** [comment]
We will start using `kpt cfg set -R` in Kubeflow 1.3 onward
