### ISSUE TITLE
Kubeflow issue on GKE

### ISSUE THREAD

**Issue by vineetbadola** [kubeflow/gcp-blueprints#181]
Team

I am trying to setup Kubeflow on GKE
I am able to setup the management cluster but facing issue while configuring the kubeflow cluster

Everytime getting below error
service/application-controller-service created
serviceaccount/application-controller-service-account created
error: unable to recognize ".build/application/app.k8s.io_v1beta1_application_application-controller-kubeflow.yaml": no matches for kind "Application" in version "app.k8s.io/v1beta1"
make: *** [Makefile:195: apply-kubeflow] Error 1

According to the document i tried many times ,but getting same error

Will be great if someone can help here

Note:I am following this article https://www.kubeflow.org/docs/gke/deploy/deploy-cli/

**Comment by Bobgy** [comment]
Transferred the issue to kubeflow/gcp-blueprints, because this is GCP specific.

**Comment by nico-kuzak** [comment]
Woke up today and it was working. Maybe it takes a while to create the secret?

**Comment by vineetbadola** [comment]
Same here

It was working after some time.Looks like it take some time for authentication

regards
vineet

**Comment by Bobgy** [comment]
Great, let's close for now. Feel free to reopen or create new issues if this shows up again

**Comment by JulesBelveze** [comment]
Just ran into the same problem and after some time it finally worked 🤔

**Comment by Lasica** [comment]
For me it was related to kubernetes version. The manifest here for version 1.6.1 is not compatible with 1.22 kubernetes api. Either downgrading or taking the newer version of Application CRD worked fine:
https://github.com/kubernetes-sigs/application
Api is no longer in beta.
