### ISSUE TITLE
Higher timeout value needed for apply-mirror function GCP cloud build job

### ISSUE THREAD

**Issue by sunilfernandes** [kubeflow/gcp-blueprints#185]
The "apply-mirror: hydrate-mirror" function in https://github.com/kubeflow/gcp-blueprints/blob/master/kubeflow/Makefile#L244 creates a GCP Cloud Build job to pull images for KF1.2. But this build job has a timeout of 10 minutes. I have ran this job multiple times and it always times out and fails.
 
I added a higher timeout value of 30 minutes (1800 seconds) and this works now.
 
https://github.com/kubeflow/gcp-blueprints/blob/master/kubeflow/Makefile#L249
 
Original :
gcloud builds submit --async gs://kubeflow-examples/image-replicate/replicate-context.tar.gz --project $(PROJECT) --config $(BUILD_DIR)/cloudbuild.yaml
 
with timeout:
 
gcloud builds submit --async gs://kubeflow-examples/image-replicate/replicate-context.tar.gz --project $(PROJECT) --config $(BUILD_DIR)/cloudbuild.yaml **--timeout=1800**
 
This build was executed in the EU region for GCP and needs atleast 20-30 mins to complete.

**Comment by Bobgy** [comment]
Thanks for figuring out the problem, do you want to submit a PR?

**Comment by sunilfernandes** [comment]
Thanks @Bobgy Created https://github.com/kubeflow/gcp-blueprints/pull/187

**Comment by sunilfernandes** [comment]
Fixed #187
