### ISSUE TITLE
Little error in guide

### ISSUE THREAD

**Issue by ulrikpl** [kubeflow/gcp-blueprints#201]
"Setting up a management cluster" step kubeflow/website#2

`cd "${MGMT_DIR}"`

In order to work it has to be:

`cd "${MGMT_DIR}"/management` 

Since the previous step downloads ${MGMT_DIR}"/management:
`kpt pkg get https://github.com/kubeflow/gcp-blueprints.git/management@v1.2.0 "${MGMT_DIR}"`

**Comment by zijianjoy** [comment]
Tip is included in https://www.kubeflow.org/docs/distributions/gke/deploy/management-setup/#fetch-kubeflowgcp-blueprints-package
