### ISSUE TITLE
Kubeflow on GCP v1.2.1 release

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/gcp-blueprints#208]
We've done the release to resolve https://github.com/kubeflow/gcp-blueprints/issues/198

**Comment by Bobgy** [comment]
Releases already made, pending doc update in https://github.com/kubeflow/website/pull/2582

**Comment by zijianjoy** [comment]
Validated that kubeflow 1.2.1 deployment is successful. Approving above PR.

**Comment by Bobgy** [comment]
Release done
