### ISSUE TITLE
[knative] Issue when building knative 0.22.0 and kustomize namespace patch

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/gcp-blueprints#217]
During KFServing installation, I am trying to upgrade KNative by following https://knative.dev/docs/install/install-serving-with-yaml/#install-the-serving-component.

Since we want to patch knative-serving namespace with ASM label, I use kustomize to patch the knative resource.

After the comment from Yuan and David: https://github.com/kubeflow/gcp-blueprints/pull/212#discussion_r615369195. I realized that serving-core.yaml has duplicated definition as serving-crd.yaml. Therefore my attempt to include both files will failed in kustomization.yaml. After the adjustment it is the structure I have:

kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./knative-0-22-0/serving-core.yaml
- ./knative-0-22-0/net-istio.yaml
namespace: knative-serving
patches:
- path: patches/namespace-patch.yaml
```

namespace-patch.yaml
```
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
  labels:
    istio.io/rev: asm-192-1 
    istio-injection: null
```

However, the build failed with the following message:

```
Error: error marshaling into JSON: json: unsupported type: map[interface {}]interface {}
```

I found that this issue seems similar https://github.com/mikefarah/yq/issues/519, but I am already using yq v3.4.1 from my end.

I also applied the customization of kfserving-core.yaml file from https://github.com/argoflow/argoflow/commit/ce115f089736b8e2988fa31029eb1d3411fc1be4, but didn't resolve the issue. I think this customization might resolve the issue I haven't encountered yet.

**Comment by DavidSpek** [comment]
This is caused by a bug in kyaml as described in [this comment](https://github.com/kubernetes-sigs/kustomize/issues/3446#issuecomment-762122084) in the following issue: https://github.com/kubernetes-sigs/kustomize/issues/3446. For now I think the easiest way forward is to simply expand the manifest.

**Comment by zijianjoy** [comment]
> This is caused by a bug in kyaml as described in [this comment](https://github.com/kubernetes-sigs/kustomize/issues/3446#issuecomment-762122084) in the following issue: [kubernetes-sigs/kustomize#3446](https://github.com/kubernetes-sigs/kustomize/issues/3446). For now I think the easiest way forward is to simply expand the manifest.

Thank you David for the reference! It makes sense and I expanded net-istio.yaml and serving-core.yaml. The kustomize build works now!

**Comment by zijianjoy** [comment]
One caveat is that I need to run multiple times of same command, because the namespace was not ready at the first run. I will do some customization to apply namespace resource first...

**Comment by DavidSpek** [comment]
You might also want to consider adding eventing but commented out as it is optional, so users can easily enable it if they want to. https://github.com/argoflow/argoflow/tree/master/knative might be handy as a reference (also for the image digests).
