### ISSUE TITLE
Simplify Makefile

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/gcp-blueprints#230]
### Motivation

We want to answer the following questions for users:

* How does user set kpt values?
* How do we define root Makefile for simplest logic.
* How does subfolder Makefile get common env variables from root Makefile?
* How does user pull from upstream while not interfering user kustomized items?
* How does user maintain the build folders?
* How does user upgrade the whole gcp-blueprints's Kubeflow manifest version? (1.3->1.4)
* How does user upgrade individual component? (For example they only want to upgrade KFserving)

### Thinking points

Some high level directions we are considering.

1. BUILD_DIR?=build for build folder path, default to each app own directory.
2. Polish deployment step.
3. individual app's apply instead of root Makefile make apply
4. call Make if Makefile exists, otherwise use kubectl.

**Comment by zijianjoy** [comment]
Structure description:

### List of components:

common/cnrm  [special-handling]
common/asm  [special-handling]
iap-secret (Command only)
common/kubeflow-namespace
common/istio
contrib/application
common/cert-manager [special-handling]
contrib/metacontroller
common/cloud-endpoints
common/iap-ingress
common/config-kubeflow
apps/admission-webhook
apps/centraldashboard
common/kubeflow-roles
apps/jupyter
apps/volumes-web-app
apps/tensorboard/tensorboards-web-app [special-handling]
apps/tensorboard/tensorboard-controller [special-handling]
apps/profiles
apps/pytorch-job
apps/tf-training
apps/pipeline
apps/kfserving
common/user-namespace
apps/katib
common/cert-manager/upstream/cert-manager/kubeflow-issuer [special-handling]

### Root kubeflow structure

`env.sh`: User defines global environment variables
`kpt-set.sh`: User set custom values for kpt using environment variables
`pull-upstream.sh`: User set the upstream manifests version, and pull all manifests to each components' `upstream/` folder.
`Makefile`: Commands: validate-values, hydrate-all, apply-all, clean-build, delete-gcp.

#### hydrate-all

input: BUILD_DIR(default is ./build), list of component paths (default value is listed above in this comment)
logic: call validate-values, then call each components' `make hydrate` target, if Makefile not exists, call kustomize build. It generates resources file to the provided BUILD_DIR path (either relative or absolute path).

#### apply-all

input: BUILD_DIR(default is ./build), list of component paths (default value is listed above in this comment)
logic: call hydrate-all, call `make apply` for list of components. If Makefile not exists, call kubectl to BUILD_DIR with KF_NAME context. This needs to execute in certain order to make sure a successful deployment.

#### clean-build

input: BUILD_DIR(default is ./build), list of component paths (default value is listed above in this comment)
logic: Remove the BUILD_DIR path (either relative or absolute path).

#### delete-gcp

input: BUILD_DIR(default is ./build)
logic: call `make delete` towards cnrm folder.

#### apply-component (in consideration)

input: BUILD_DIR(default is ./build), component path.
logic: call `make hydrate`, `make apply` to target component path. If Makefile not exists, call kubectl directly.


### Individual component structure

`Makefile`: Optional. If exists: commands are: hydrate, apply, clean-build, delete
`kustomization.yaml`: This file needs to exist. User can change this file for GCP project specific customization.
`patches`: This folder is created for gcp deployment.
`upstream`: This folder is pulled from `kubeflow/manifests` by pull-upstream.sh


#### hydrate

input: BUILD_DIR(default is ./build)
logic: It generates resources file to the provided BUILD_DIR path (either relative or absolute path).

#### apply

input: BUILD_DIR(default is ./build)
logic: get environment variables, it will apply the resources based on specific needs.

#### clean-build

input: BUILD_DIR(default is ./build)
logic: remove build files

#### delete (optional)

input: BUILD_DIR(default is ./build)
logic: uninstall resources from BUILD_DIR

#### upgrade

Specific logic to upgrade this component's version.

### Questions to be answered

How to pass variables like KF_NAME, BUILD_DIR, etc. to each components' folders?

cc @Bobgy

**Comment by Bobgy** [comment]
> How to pass variables like KF_NAME, BUILD_DIR, etc. to each components' folders?
How to upgrade Makefile, pull-upstream.sh, patches/ folder, etc. for users?

One way to do it is passing by environment variable, let individual components assume some env vars exists.

**Comment by zijianjoy** [comment]
Thank you Yuan for the suggestion! For the first attempt, I am going to pass environment variable. I tried to use kpt setter but at some cases it cannot read kpt value correctly. (Maybe it requires Kptfile to contain those values)

**Comment by zijianjoy** [comment]
Realized that Knative serving requires Kubernetes 1.18+ https://knative.dev/docs/install/prerequisites/#prerequisites

**Comment by Bobgy** [comment]
thanks, I wasn't aware of the knative serving constraint.
we might need to go back to UNSPECIFIED channel with 1.18 as min version

**Comment by zijianjoy** [comment]
> thanks, I wasn't aware of the knative serving constraint.
> we might need to go back to UNSPECIFIED channel with 1.18 as min version

Thank you for confirming! May I ask why we cannot use STABLE channel if we use 1.18 k8s version?

**Comment by zijianjoy** [comment]
https://github.com/kubeflow/gcp-blueprints/pull/235
https://github.com/kubeflow/gcp-blueprints/pull/238

**Comment by Bobgy** [comment]
When you pin a channel, the channel decides your version, you cannot change at all.

**Comment by zijianjoy** [comment]
> When you pin a channel, the channel decides your version, you cannot change at all.

I tried GCP console to select STABLE release channel, we still have a few options of k8s versions to select from. Is this the limitation you are mentioning?
![stablechanneloption](https://user-images.githubusercontent.com/37026441/116341961-acbe0780-a796-11eb-9840-6a4242350f09.png)

**Comment by Bobgy** [comment]
Interesting, then I am wrong. If that's possible, we can do this

**Comment by Bobgy** [comment]
component apply failure should exit right away
