### ISSUE TITLE
managed project namespace not found

### ISSUE THREAD

**Issue by edi-bice-by** [kubeflow/gcp-blueprints#282]
edi_bice@general-instance-2:~/gcp-blueprints/kubeflow$ make apply
cluster_name_regex=^[a-z][-a-z0-9]{0,22}[a-z0-9]$
The kubeflow cluster name "kubeflow" is valid.
PROJECT=saas-ml-dev NAME=kubeflow ./hack/check_domain_length.sh
Build directory: ./build
Component path: common/managed-storage
Apply component resources: common/managed-storage
Found Makefile, call 'make apply' of this component Makefile. 
make[1]: Entering directory '/home/edi_bice/gcp-blueprints/kubeflow/common/managed-storage'
rm -rf ./build
mkdir -p ./build
kustomize build -o ./build/ .
kubectl --context=kf-mgmt apply -f ./build
Error from server (NotFound): error when creating "build/sql.cnrm.cloud.google.com_v1beta1_sqlinstance_kubeflow-kfp.yaml": namespaces "saas-ml-dev" not found
Error from server (NotFound): error when creating "build/storage.cnrm.cloud.google.com_v1beta1_storagebucket_saas-ml-dev-kfp.yaml": namespaces "saas-ml-dev" not found
Makefile:35: recipe for target 'apply-cnrm' failed
make[1]: *** [apply-cnrm] Error 1
make[1]: Leaving directory '/home/edi_bice/gcp-blueprints/kubeflow/common/managed-storage'
Makefile:67: recipe for target 'apply' failed
make: *** [apply] Error 1

**Comment by edi-bice-by** [comment]
Steps described here fix the issue but I think it's best to keep this issue open until the steps are incorporated into the Makefile

https://github.com/kubeflow/gcp-blueprints/issues/257#issuecomment-833838222

**Comment by Bobgy** [comment]
Hi @edi-bice-by , we have the steps documented in https://www.kubeflow.org/docs/distributions/gke/deploy/deploy-cli/#management-cluster-config.
Did I miss anything?

**Comment by edi-bice-by** [comment]
@Bobgy okay I'll close the issue then
