### ISSUE TITLE
Management cluster on GCP issue - googleapi: Error 400: Private cluster config can only be set on private clusters.

### ISSUE THREAD

**Issue by rajsrujan77** [kubeflow/gcp-blueprints#289]
Hi,

I was trying to deploy Kubeflow on GCP using the [official Documentation](https://www.kubeflow.org/docs/distributions/gke/deploy/management-setup/). I was facing the below issue in the initial management cluster creation step. Was stuck here and couldn't find a resolution to it.

```
(test_env) Rajs-MacBook-Air:management raj$ make apply-cluster
The management cluster name "kubeflow-manage" is valid.
# Delete the directory so any resources that have been removed
# from the manifests will be pruned
rm -rf build/cluster
mkdir -p build/cluster
kustomize build ./cluster -o build/cluster
# Create the cluster
anthoscli apply -f build/cluster
I0618 22:50:50.865759   93264 main.go:230] reconcile serviceusage.cnrm.cloud.google.com/Service container.googleapis.com
I0618 22:50:56.670874   93264 main.go:230] reconcile container.cnrm.cloud.google.com/ContainerCluster kubeflow-manage
Unexpected error: error reconciling objects: error reconciling ContainerCluster:<project-name>/kubeflow-manage: error creating GKE cluster kubeflow-manage: googleapi: Error 400: Private cluster config can only be set on private clusters.
make: *** [apply-cluster] Error 1
```

Thanks. :)

**Comment by susan-shu-c** [comment]
Seems related to #291

**Comment by zijianjoy** [comment]
I am able to reproduce the error and you need to upgrade anthoscli to resolve this issue:

Run following command:
`gcloud components update`

Then check your anthoscli version:
`anthoscli version`

The working version is:
`Version: version.Version{AnthosCLIVersion:"beta", GitCommit:"564e63c8e3df42c8b3105cad334eb198996a18a8", GitTag:"0.2.17", BuildDate:"2021-06-17T13:21:04Z", GoOs:"linux", GoArch:"amd64"}`

Would you like to confirm if this fixes your issue?
