### ISSUE TITLE
GKE Ingress Bad Gateway or Backend not found

### ISSUE THREAD

**Issue by dotnetpiper** [kubeflow/gcp-blueprints#290]
Hi Team,

I've been using GKE and setup GKE Ingress mere to manage the path for all images which we have kept in GCR.
I've created a .Net core based API which is has various path , if I expose the deployment with service as type Loadbalancer it works perfectly. Though when I utilize GKE Ingress and setup service and its backend it throws an error like Bad Gateway or sometime backend not found.

.Net core api application exposes following path when i exposed on service as loadbalancer, kindly follow below screenshot for reference:
http://35.202.38.40/api/books
http://35.202.38.40/api/categories

![image](https://user-images.githubusercontent.com/20516546/122713942-24368180-d284-11eb-9161-944cf413e4c9.png)

The same way we do have post api's.

Now I'm stuck when I utilize GKE ingress and setup my ingress.yaml as follows , it doesn't work and throws an error.
Ingress.Yaml

`apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gke-ingress
  annotations:
    # If the class annotation is not specified it defaults to "gce".
    kubernetes.io/ingress.class: "gce"    
spec:  
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:          
            serviceName: hello-world
            servicePort: 80
      - path: /api/*       
        backend:          
            serviceName: hello-world
            servicePort: 80      `

NOTE: my hello-word is exposing a .Net Core API application, kindly don't get confuse with name as "hello-world" for testing.
![image](https://user-images.githubusercontent.com/20516546/122714467-faca2580-d284-11eb-9e27-caa23622b942.png)

Deployment and service Yaml

`apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  selector:
    matchLabels:
      greeting: hello
      department: world
  replicas: 2
  template:
    metadata:
      labels:
        greeting: hello
        department: world
    spec:
      containers:
      - name: hello
        image: gcr.io/strategic-uop-322987/bookapp:631
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: NodePort
  selector:
    greeting: hello
    department: world
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80`

Kindly advise how to setup path based routing in GKE Ingress for .Net Core Api app.

**Comment by Bobgy** [comment]
Hi @dotnetpiper the question does not seem to be related to Kubeflow.
Can you ask Cloud Support for help?
