### ISSUE TITLE
Cannot deploy Management Cluster - Error 400: Private cluster config can only be set on private clusters.

### ISSUE THREAD

**Issue by andrea-cola** [kubeflow/gcp-blueprints#291]
I'm trying to install the management cluster but I receive the following error when I use the command: `make apply`.

```
reconcile container.cnrm.cloud.google.com/ContainerCluster kubem
Unexpected error: error reconciling objects: error reconciling ContainerCluster:adq-317109/kubem: error creating GKE cluster kubem: googleapi: Error 400: Private cluster config can only be set on private clusters.
```

I already updated all my libraries, and followed step by step the guide on Kubeflow website.

Envinroment: GCP

**Comment by susan-shu-c** [comment]
Hi, have encountered this issue as well. GCP user. Same error while trying to deploy management cluster, was working fine last Friday.

**Comment by zijianjoy** [comment]
@andrea-cola @susan-shu-c 

Thank you for reporting this issue! I am able to reproduce the error and you need to upgrade anthoscli to resolve this issue:

Run following command:
`gcloud components update`

Then check your anthoscli version:
`anthoscli version`

The working version is:
`Version: version.Version{AnthosCLIVersion:"beta", GitCommit:"564e63c8e3df42c8b3105cad334eb198996a18a8", GitTag:"0.2.17", BuildDate:"2021-06-17T13:21:04Z", GoOs:"linux", GoArch:"amd64"}`

**Comment by PatrickGhosn** [comment]
> @andrea-cola @susan-shu-c
> 
> Thank you for reporting this issue! I am able to reproduce the error and you need to upgrade anthoscli to resolve this issue:
> 
> Run following command:
> `gcloud components update`
> 
> Then check your anthoscli version:
> `anthoscli version`
> 
> The working version is:
> `Version: version.Version{AnthosCLIVersion:"beta", GitCommit:"564e63c8e3df42c8b3105cad334eb198996a18a8", GitTag:"0.2.17", BuildDate:"2021-06-17T13:21:04Z", GoOs:"linux", GoArch:"amd64"}`
> 
> Would you like to confirm if this fixes your issue?

Thank you @zijianjoy ! This fixed it. :D

**Comment by andrea-cola** [comment]
Thank you @zijianjoy ! Also in my case this fix it. :)
