### ISSUE TITLE
Where can I find the latest image for centraldashboard on gcr?

### ISSUE THREAD

**Issue by daikeshi** [kubeflow/gcp-blueprints#292]
We are using centraldashboard image published to `gcr.io/kubeflow-images-public/centraldashboard`, but it seems the images there haven't been updated since Aug, 2020. 

In `kubeflow/manifest` repo, the centraldashboard image is fetched from AWS at `public.ecr.aws/j1r0q0g6/notebooks/central-dashboard` but it seems I don't have the access. 

Can we still expect future centraldashboard images will be available on gcr? or we fetch them from a different place? If so, what's the process? Thank you!

**Comment by Bobgy** [comment]
@daikeshi I am not sure why you don't have access, you may ask notebooks maintainers, because they own central dashboard now.

Also, going forward each working group will be responsible for hosting their images. They won't be on gcr in the futures

**Comment by daikeshi** [comment]
@Bobgy gotcha! I'll check with notebook maintainers. Thank you!

When I tried to directly visit the image from a browser, I got the following error 🤔 
```
public.ecr.aws/j1r0q0g6/notebooks/central-dashboard
```
