### ISSUE TITLE
no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"

### ISSUE THREAD

**Issue by edi-bice-by** [kubeflow/gcp-blueprints#333]
pulled latest from master 88d5cdddf85c819c1129cf36e8d1560a1785885a

deploying fresh cluster (different name after failed upgrade of existing cluster, clean up etc)

make apply produces

error: unable to recognize "common/istio/build/networking.istio.io_v1alpha3_gateway_kubeflow-gateway.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"

**Comment by edi-bice-by** [comment]
Okay, this was my making. 

Working on MacOS, it seems asm/install_asm needs and downloads a specific older version of kpt which it then cannot find and uses global PATH one.

So I modified install_asm script to find what kpt it needs and ran it manually. Later commented out asm in config.yaml components list so make apply would skip it.

After many tries and retries I cleaned up cluster tried a fresh one but forgot to uncomment asm in components.

**Comment by zijianjoy** [comment]
What is the ASM version you used? Is it related to https://github.com/kubeflow/gcp-blueprints/issues/260?

**Comment by edi-bice-by** [comment]
@zijianjoy I suppose you can say it's related to #260 in that it all seems to be due to MacOs - bit the bullet and set up a Linux VM. Everything worked much, much better then. I thought I was doing manually all that needed to be done but maybe I missed some stuff.
