### ISSUE TITLE
unknown command "r" for "yq"

### ISSUE THREAD

**Issue by edi-bice-by** [kubeflow/gcp-blueprints#334]
using 1.4 tag

make[1]: Entering directory '/home/ubuntu/gcp-blueprints/kubeflow/common/iap-ingress'
rm -rf ./build && mkdir -p ./build
Error: unknown command "r" for "yq"
Run 'yq --help' for usage.

ubuntu@primary:~/gcp-blueprints/kubeflow/common/iap-ingress$ grep yq *
Makefile:NAME=$(shell yq r ../../kptconfig/kpt-setter-config.yaml 'data.name')

**Comment by edi-bice-by** [comment]
Fixed 

`diff --git a/kubeflow/common/iap-ingress/Makefile b/kubeflow/common/iap-ingress/Makefile
index c7797eb..fbb9b48 100644
--- a/kubeflow/common/iap-ingress/Makefile
+++ b/kubeflow/common/iap-ingress/Makefile
@@ -1,5 +1,5 @@
 build_dir?=./build
-NAME=$(shell yq r ../../kptconfig/kpt-setter-config.yaml 'data.name')
+NAME=$(shell yq '.data.name' ../../kptconfig/kpt-setter-config.yaml)
 # The kubectl context for your Kubeflow cluster
 KFCTXT=$(NAME)`

**Comment by zijianjoy** [comment]
Potential fix: https://github.com/kubeflow/gcp-blueprints/blob/18bf45ad832712bc64bfd9428718dddc0823f8e1/kubeflow/common/cnrm/Makefile#L4-L5

**Comment by zijianjoy** [comment]
Hello @edi-bice-by , can you try replacing the following line in https://github.com/kubeflow/gcp-blueprints/blob/master/kubeflow/common/iap-ingress/Makefile#L2 to: 

```
 YQ=docker run --rm -v "$(PACKAGE_DIR)/":/workdir mikefarah/yq:4 
 NAME=$(shell $(YQ) e '.data.name' kptconfig/kpt-setter-config.yaml) 
```

If this works, would you like to create a pull request for the fix? Thank you!

**Comment by edi-bice-by** [comment]
@zijianjoy the patch I posted earlier worked as I replicated with yq4 what yq3 was doing.

Was able to finally deploy 1.4 and don't want to mess with it.

I see your code does the same thing so it will work as well. Will try a pull request.
