### ISSUE TITLE
Kubeflow 1.4 installation : error when creating cert-manager

### ISSUE THREAD

**Issue by jal06** [kubeflow/gcp-blueprints#336]
I try to install Kubeflow 1.4 in my GCP project according to [documentation](https://v1-4-branch.kubeflow.org/docs/distributions/gke/deploy/)

When executing "`make apply`" (step Deploy Kubeflow) , I get the below error :

```
# Common kubeflow-issuer
kubectl --context=kfv4 apply -f ./build/kubeflow-issuer
Error from server (InternalError): error when creating "build/kubeflow-issuer/cert-manager.io_v1alpha2_clusterissuer_kubeflow-self-signing-issuer.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": No SSH tunnels currently open.
```

Has anyone experienced similar kind of problem and what are the best ways to troubleshoot and solve the problem?

Some additional informations :

The version of the management cluster is 1.21.5-gke.1302 
The version of the kubeflow cluster is 1.20.10-gke.1600

kubectl version 1.20.10
kustomize version : 4.0.5
kpt version : 1.0.0-beta.7
gcloud version : 365.0.1

Thanks for your help .

**Comment by zijianjoy** [comment]
Would you like to check if you have right configuration as in https://stackoverflow.com/questions/36375030/kubectl-error-from-server-no-ssh-tunnels-currently-open?

**Comment by jal06** [comment]
@zijianjoy thanks for your reply.

I had a look at the stackoverflow you mentioned, that's the same error, but :
1- 2 nodes are successfully deployed in my KF cluster
2- in my KF cluster, all the deployed pods are running (1 pod in namespace asm-system, 3 pods in namespace cert-manager, 4 pods in namespace istio-system, 23 pods in namespace kube-system, 0 pod in namespace kubeflow )
3- I didn't change anything on the firewall rules
4- I checked the length of the metadate entry named "sshKeys" and I am far from 32K limit. Moreover, I can see the entries named "ssh" for the management cluster and the kubeflow cluster. I can also see the entry  key for user gke-xxxxxxxxx.
5- I have not set a metadata field with the key "sshKeys" on the VMs in the cluster
6- I didn't turn on the OS login

Just a point I noticed  : I tried to delete the KF instance following the [Kubeflow documentation](https://v1-4-branch.kubeflow.org/docs/distributions/gke/deploy/delete-cli/) 
When I try to delete the kubeflow namespace (which is empty), the kubectl commands hangs and the kubeflow namespace stucks as "Terminating".

Before trying to delete the namespace kubeflow, I checked the objects deployed in this namespace 
`kubectl get all -n kubeflow`
returns
`No resources found in kubeflow namespace.`

I don't understand why the kubeflow namespace stucks as "Terminating" in the KF cluster.
Is there something else I could check ?

**Comment by zijianjoy** [comment]
Hello @jal06 , the SSH connection seems to be related to Compute Engine, rather than Kubeflow. I am suspecting the issue might be transient because there might be some upgrade/repair happening on your cluster. You might need to reconnect to your Kubernetes Cluster. 

I think it is due to connectivity issue so you didn't have any resource in kubeflow namespace. You might need to rerun `make apply`.

**Comment by jal06** [comment]
Hello @zijianjoy,

A network admin told me that he applied some additional network rules a few days ago.
I am going to investigate in this direction

Thanks very much for your help.

**Comment by zijianjoy** [comment]
Thanks for the update @jal06 . Once you find the solution, you can close this issue.

**Comment by jal06** [comment]
My GCP project has been deleted.
Closing this issue now because I am unable to do more investigations. Thanks for your help.
