### ISSUE TITLE
Documentation update for Kubeflow 1.5 on Google Cloud

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/gcp-blueprints#341]
- [x] 1. Needs to follow https://www.kubeflow.org/docs/distributions/gke/deploy/deploy-cli/#authorize-cloud-config-connector-for-each-kubeflow-project regardless of multi-project 
- [x] 2. Use shortcode for Kubeflow version on GCP: https://github.com/kubeflow/website/blob/master/layouts/shortcodes/pipelines/latest-version.html
- [x] 3. Upgrade version to 1.5.
- [ ] 4. We might need to specify the required tools by ASM (jq is required by ASM)
- [x] 5. Config Controller migration might require documentation update.
- [ ] ~~6. ASM enablement is different now.~~
- [ ] 7. Update Kubeflow upgrade and destroy guide.

**Comment by shannonbradshaw** [comment]
@zijianjoy we are getting ready to cut the docs branch. Where are we on items 2, 4, and 6 above?

**Comment by zijianjoy** [comment]
@shannonbradshaw PR is made for https://github.com/kubeflow/website/pull/3195
