### ISSUE TITLE
cloud-endpoints-controller:0.2.1 does not exist

### ISSUE THREAD

**Issue by piernikR** [kubeflow/gcp-blueprints#343]
When trying to deploy kubeflow 1.4 on GCP using the official guides https://www.kubeflow.org/docs/distributions/gke/deploy/deploy-cli/ 
the image "gcr.io/cloud-solutions-group/cloud-endpoints-controller:0.2.1" is not available. As a result, the endpoint controller pod does not start and the UI interface is not accessible.

**Comment by zijianjoy** [comment]
Thank you so much for the report!

I contacted the image owners and we have changed the image location to mitigate the issue. Please follow the steps below:

### Mitigation 

For the lines in these locations: https://github.com/kubeflow/gcp-blueprints/search?q=cloud-solutions-group
1. Change `gcr.io/cloud-solutions-group/cloud-endpoints-controller` to `gcr.io/ml-pipeline/cloud-solutions-group/cloud-endpoints-controller`.
2. Change `gcr.io/cloud-solutions-group/esp-sample-app` to `gcr.io/ml-pipeline/cloud-solutions-group/esp-sample-app`.
3. Re-deploy the corresponding components: `iap-ingress`, `cloud-endpoints`

**Comment by zijianjoy** [comment]
Urgent release is now made. You can start using v1.4.1 for Kubeflow deployment on Google Cloud: https://github.com/kubeflow/gcp-blueprints/releases/tag/v1.4.1

**Comment by zijianjoy** [comment]
Urgent release is made: https://github.com/kubeflow/gcp-blueprints/releases/tag/v1.4.1, you can now use v1.4.1 tag for deployment.
