### ISSUE TITLE
Make regional deployments work; what to do about the disks for metadata

### ISSUE THREAD

**Issue by jlewi** [kubeflow/gcp-blueprints#6]
We would like to support regional deployments of Kubeflow; i.e. use a regional cluster. Ideally this would be the default deployment since regional clusters are more reliable and there is minimal cost savings to using a zonal cluster.

One issue we need to resolve is what to do about the disks backing up the metadata DB.

We should be able to use regional PDs.
https://cloud.google.com/compute/docs/disks/high-availability-regional-persistent-disk

EDIT: please thumbs up on the issue if it's important to you.

**Comment by jtfogarty** [comment]
/kind feature
priority p2

**Comment by damitkwr** [comment]
Is there an update on work for this as this is a highly desirable feature for enterprise installations

**Comment by Bobgy** [comment]
> Is there an update on work for this as this is a highly desirable feature for enterprise installations

Hi @damitkwr, thanks for your interest. Thumbs up on the issue give us more metrics to prioritize them.

**Comment by susan-shu-c** [comment]
Interested in regional as well!

**Comment by Bobgy** [comment]
We've supported regional clusters in Kubeflow 1.3 on Google Cloud by switching to use CloudSQL + GCS by default.
