### ISSUE TITLE
Fix workload identity tests 

### ISSUE THREAD

**Issue by jlewi** [kubeflow/gcp-blueprints#82]
Workload identity tests are failing for both 1.1 and master branch. The error is

```
  raise HttpError(resp, content, uri=self.uri)
E           googleapiclient.errors.HttpError: <HttpError 404 when requesting https://iam.googleapis.com/v1/projects/kubeflow-ci-deployment/serviceAccounts/-admin@kubeflow-ci-deployment.iam.gserviceaccount.com:getIamPolicy?alt=json returned "Service account projects/kubeflow-ci-deployment/serviceAccounts/-admin@kubeflow-ci-deployment.iam.gserviceaccount.com does not exist.">
```

This is a bug in the test. We aren't passing in the correct name for the service account.

related to: 46

**Comment by jlewi** [comment]
Here's a passing manual run
https://kf-ci-v1.endpoints.kubeflow-ci.cloud.goog/tekton/#/namespaces/kf-ci-dev/pipelineruns/gcp-kf-ready-j5zz7

Requires changes in kubeflow/testing#732 we may need to rehydrate and commit because of changes in conflicting PRs.

**Comment by jlewi** [comment]
Test is still failing.

```
   googleapiclient.errors.HttpError: <HttpError 404 when requesting https://iam.googleapis.com/v1/projects/kubeflow-ci-deployment/serviceAccounts/-admin@kubeflow-ci-deployment.iam.gserviceaccount.com:getIamPolicy?alt=json returned "Service account projects/kubeflow-ci-deployment/serviceAccounts/-admin@kubeflow-ci-deployment.iam.gserviceaccount.com does not exist.">
```

Do we need to rehydrate?

The mnist notebook is running successfully; so downgrading to P1 and saying this isn't release blocking.

**Comment by Bobgy** [comment]
fixed
