### ISSUE TITLE
Move patches in instance into kubeflow/manifests  stacks

### ISSUE THREAD

**Issue by jlewi** [kubeflow/gcp-blueprints#94]
Right now we have a bunch of patches in the instance directory; e.g.
https://github.com/kubeflow/gcp-blueprints/tree/master/kubeflow/instance/kustomize/iap-ingress
https://github.com/kubeflow/gcp-blueprints/tree/master/kubeflow/instance/kustomize/kubeflow-apps

Is there a reason to store these in the instance directory? As opposed to moving into the package that gets stored in upstream
and using kpt setters to configure them?

I guess the question is where would they live? I think the purpose of these patches is to provide GCP specific overlays for specific applications. Should we just create appropriate overlays in the appropriate application and then reference those?

**Comment by Bobgy** [comment]
From my understanding, the things in `instance` are those we expect users may want to customize by themselves and they should keep them during upgrade.

e.g. https://github.com/kubeflow/gcp-blueprints/blob/master/kubeflow/instance/kustomize/kubeflow-apps/pipeline-minio-install-config.yaml and https://github.com/kubeflow/gcp-blueprints/blob/master/kubeflow/instance/kustomize/kubeflow-apps/pipeline-mysql-install-config.yaml are clearly for this purpose. We want to make it clear how to override underlying gcePd's names.

https://github.com/kubeflow/gcp-blueprints/blob/master/kubeflow/instance/kustomize/kubeflow-apps/default-install-config.yaml is kind of awkward to me, shall we remove the default config and let user create their own when visiting UI?

For https://github.com/kubeflow/gcp-blueprints/blob/master/kubeflow/instance/kustomize/kubeflow-apps/service-accounts.yaml, I agree we should move it to upstream/manifest

**Comment by Bobgy** [comment]
Latest decision is to remove instance folder and move everything to upstream. When users need an instance folder they can set up the structure by themselves.
